#dont touch
version: "1.0"
#Use this to enable protection in the lobby
#Players won't be able to build or break stuff when enabled and in the lobby
enable-protection: true
#Use this to regenerate arenas after they've finished
#usefull if protection in-game is disabled
#DO NOT ENABLE THIS IF YOU HAVE VERY LARGE ARENAS!!!!(over 1,000,000 blocks inside)
#IT WILL CAUSE LOTS OF LAG WITH HUGE ARENAS
regenerate-arena-after-finishing: false
#Automatically converts any block-based usage (e.g. teleportation)
#to the center of the block. It also will change yaw & pitch to the
#nearest 90 degrees if a rotation value is used.
centerize-teleport-locations: true
#Enable the custom chat features
#sendGameMessagesToAll will output game messages to everyone on the server
#For format, use %player% for the playername and %message% for the sent message  
Chat:
  enable: false
  sendGameMessagesToAll: false
  format: "&2[&eISGChat&2] &7%player% &f&l--> &r&b%message%"
#Enable the tablist features
#Header and footer are what the top and bottom of the list show as
#hidePlayersNotInGame (when enabled) will only show players in your tablist that are in the same arena as you.
#hidePlayersInGameFromServer (when enabled) removes players in-game from everyone else's tablist
# both hide options are disabled completly and do nothing as of now
Tablist:
    enable: false
    header: "&7[&6IngotSurvivalGames&7]"
    hidePlayersNotInGame: true
    hidePlayersInGameFromServer: true
    footer: "&bPlaying on &aMy &lAwesome&r&a Server&b!"
#Enable the scoreboard features
#maxLines is the siz elimit for the scoreboard
#Title is the name of the scoreboard
#You can create your own lines in here. just type "Line(1-15): (text)"
#Use %currentplayers% to get the amount of players in game, and %maxplayers% for the max amount of players
Scoreboard:
    enable: false
    maxLines: 5
    title: "&7[&6IngotSurvivalGames&7]"
    line1: "&bPlayers InGame: &c%currentplayers% &7/ &c%maxplayers%"
    line3: "&aMy Awesome Server!"
#Enable the tile features
#title sets the main title
#subtitle sets the title
#actionbar sets the text above the hotbar
#fadeIn and out set how long the fades should be
#length sets how long the title and subtitle last (doesnt affect actionbar)
#all values are in ticks (1/20th sec)
Title:
    enable: false
    Join:
        title: '&aYou have joined the game'
        subtitle: '&bHave Fun!'
        actionbar: 'Plugin by Budderman18'
        fadein: 10
        length: 100
        fadeout: 10
    Start:
        title: "&aThe game starts in &e"
        subtitle: ""
        actionbar: ""
        fadein: 10
        length: 60
        fadeout: 10
    Leave:
        title: '&aYou have left the game'
        subtitle: '&bDon''t do that!'
        actionbar: 'Plugin by Budderman18'
        fadein: 10
        length: 100
        fadeout: 10
    InGameStart:
        title: "&aThe game starts in &e"
        subtitle: ""
        actionbar: ""
        fadein: 10
        length: 60
        fadeout: 10
    InGameRelease:
        title: "&aSTART!"
        subtitle: ""
        actionbar: ""
        fadein: 10
        length: 60
        fadeout: 10
    Death:
        title: "&aYou died and are out of the game!"
        subtitle: "&bFeel free to spectate!"
        actionbar: ""
        fadein: 10
        length: 60
        fadeout: 10
    End:
        title: "&aThe game is over!"
        subtitle: "&aGood Game Everyone!"
        actionbar: "Come back soon!"
        fadein: 10
        length: 100
        fadeout: 10
#Enable the bossbar features
#sizeChangesBasedOnTimeLeft will decrease the bossbar as the match goes on.
#title sets the title
#color sets the color
#You can use blue, green, pink, purple, red, yellow and white
Bossbar:
    enable: false
    sizeChangesBasedOnTimeLeft: true
    title: "&eMy Awesome Server!"
    color: "GREEN"
#Create your own tables to randomize arena joining!
#Usefull for servers with different team sizes
#Enable chosses weather or not tables will be used
#If disabled, it'll just randomly join all listed arenas
#tables: <-- put tables below here
#  Table1: <--Table followed by next number (MUST BE IN NUMERIC ORDER!!!)
#    name: JoeMama <--name of your table(used for Tab-completion)
#    arenas: <-- arenas to randomize
#    - arena1
#    - arena2
RandomJoin:
  enable: false
  Table1:
    name: JoeMama
    arenas:
    - arena1
    - arena2
#Enable the spectator features
#changeGamemode sets spectators into spectator mode and resets them back when they leave
#if disabled, players will still be teleported to the spectator pos, just in the same gamemode
#useful for shorter games with limited camera angles
Spectate:
  enable: true
  changeGamemode: true